model:
  name: google/gemma-3-27b-pt
  type: gemma3
  hidden_dim: 5376
  shard_pattern: model-00001-of-00012.safetensors
  embedding_layer_name: language_model.model.embed_tokens.weight
languages:
  afr_Latn: 0
  als_Latn: 1
  amh_Ethi: 2
  arb_Arab: 3
  arz_Arab: 4
  asm_Beng: 5
  ayr_Latn: 6
  azj_Latn: 7
  bak_Cyrl: 8
  ban_Latn: 9
  bel_Cyrl: 10
  bem_Latn: 11
  ben_Beng: 12
  bho_Deva: 13
  bjn_Arab: 14
  bul_Cyrl: 15
  cat_Latn: 16
  ceb_Latn: 17
  ces_Latn: 18
  ckb_Arab: 19
  cmn_Hans: 20
  cmn_Hant: 21
  crh_Latn: 22
  cym_Latn: 23
  dan_Latn: 24
  deu_Latn: 25
  dzo_Tibt: 26
  ekk_Latn: 27
  ell_Grek: 28
  eng_Latn: 29
  epo_Latn: 30
  eus_Latn: 31
  ewe_Latn: 32
  fao_Latn: 33
  fij_Latn: 34
  fil_Latn: 35
  fin_Latn: 36
  fra_Latn: 37
  fur_Latn: 38
  gaz_Latn: 39
  gla_Latn: 40
  gle_Latn: 41
  gug_Latn: 42
  guj_Gujr: 43
  hat_Latn: 44
  hau_Latn: 45
  heb_Hebr: 46
  hin_Deva: 47
  hrv_Latn: 48
  hun_Latn: 49
  hye_Armn: 50
  ibo_Latn: 51
  ilo_Latn: 52
  ind_Latn: 53
  isl_Latn: 54
  ita_Latn: 55
  jav_Latn: 56
  jpn_Jpan: 57
  kab_Latn: 58
  kan_Knda: 59
  kas_Arab: 60
  kat_Geor: 61
  kaz_Cyrl: 62
  khk_Cyrl: 63
  khm_Khmr: 64
  kik_Latn: 65
  kir_Cyrl: 66
  kmr_Latn: 67
  knc_Arab: 68
  knc_Latn: 69
  kor_Hang: 70
  ktu_Latn: 71
  lao_Laoo: 72
  lim_Latn: 73
  lin_Latn: 74
  lit_Latn: 75
  ltz_Latn: 76
  lua_Latn: 77
  lug_Latn: 78
  lus_Latn: 79
  lvs_Latn: 80
  mal_Mlym: 81
  mar_Deva: 82
  mkd_Cyrl: 83
  mlt_Latn: 84
  mni_Beng: 85
  mos_Latn: 86
  mri_Latn: 87
  mya_Mymr: 88
  nld_Latn: 89
  nob_Latn: 90
  npi_Deva: 91
  nus_Latn: 92
  nya_Latn: 93
  oci_Latn: 94
  ory_Orya: 95
  pag_Latn: 96
  pan_Guru: 97
  pap_Latn: 98
  pbt_Arab: 99
  pes_Arab: 100
  plt_Latn: 101
  pol_Latn: 102
  por_Latn: 103
  quy_Latn: 104
  ron_Latn: 105
  run_Latn: 106
  rus_Cyrl: 107
  sag_Latn: 108
  san_Deva: 109
  sat_Olck: 110
  shn_Mymr: 111
  sin_Sinh: 112
  slk_Latn: 113
  slv_Latn: 114
  smo_Latn: 115
  sna_Latn: 116
  snd_Arab: 117
  som_Latn: 118
  spa_Latn: 119
  srp_Cyrl: 120
  sun_Latn: 121
  swe_Latn: 122
  swh_Latn: 123
  tam_Taml: 124
  taq_Tfng: 125
  tat_Cyrl: 126
  tel_Telu: 127
  tgk_Cyrl: 128
  tha_Thai: 129
  tir_Ethi: 130
  tpi_Latn: 131
  tsn_Latn: 132
  tso_Latn: 133
  tuk_Latn: 134
  tum_Latn: 135
  tur_Latn: 136
  twi_Latn: 137
  uig_Arab: 138
  ukr_Cyrl: 139
  urd_Arab: 140
  uzn_Latn: 141
  vec_Latn: 142
  vie_Latn: 143
  war_Latn: 144
  xho_Latn: 145
  yor_Latn: 146
  yue_Hant: 147
  zsm_Latn: 148
  zul_Latn: 149
inference:
  max_sequence_length: 512
  pooling: logsumexp
