model:
  name: "google/gemma-3-27b-pt"
  type: "gemma3"
  hidden_dim: 5376
  shard_pattern: "model-00001-of-00012.safetensors"
  embedding_layer_name: "language_model.model.embed_tokens.weight"

languages:
  # All 204 languages from OpenLID-v2 dataset
  # Format: language_Script (e.g., eng_Latn = English in Latin script)
  ace_Arab: 0
  ace_Latn: 1
  acm_Arab: 2
  acq_Arab: 3
  aeb_Arab: 4
  afr_Latn: 5
  als_Latn: 6
  amh_Ethi: 7
  apc_Arab: 8
  arb_Arab: 9
  ars_Arab: 10
  ary_Arab: 11
  arz_Arab: 12
  asm_Beng: 13
  ast_Latn: 14
  awa_Deva: 15
  ayr_Latn: 16
  azb_Arab: 17
  azj_Latn: 18
  bak_Cyrl: 19
  bam_Latn: 20
  ban_Latn: 21
  bel_Cyrl: 22
  bem_Latn: 23
  ben_Beng: 24
  bho_Deva: 25
  bjn_Arab: 26
  bjn_Latn: 27
  bod_Tibt: 28
  bos_Latn: 29
  bug_Latn: 30
  bul_Cyrl: 31
  cat_Latn: 32
  ceb_Latn: 33
  ces_Latn: 34
  cjk_Latn: 35
  ckb_Arab: 36
  cmn_Hans: 37
  cmn_Hant: 38
  crh_Latn: 39
  cym_Latn: 40
  dan_Latn: 41
  deu_Latn: 42
  dik_Latn: 43
  dyu_Latn: 44
  dzo_Tibt: 45
  ekk_Latn: 46
  ell_Grek: 47
  eng_Latn: 48
  epo_Latn: 49
  eus_Latn: 50
  ewe_Latn: 51
  fao_Latn: 52
  fij_Latn: 53
  fil_Latn: 54
  fin_Latn: 55
  fon_Latn: 56
  fra_Latn: 57
  fur_Latn: 58
  fuv_Latn: 59
  gaz_Latn: 60
  gla_Latn: 61
  gle_Latn: 62
  glg_Latn: 63
  gug_Latn: 64
  guj_Gujr: 65
  hat_Latn: 66
  hau_Latn: 67
  heb_Hebr: 68
  hin_Deva: 69
  hne_Deva: 70
  hrv_Latn: 71
  hun_Latn: 72
  hye_Armn: 73
  ibo_Latn: 74
  ilo_Latn: 75
  ind_Latn: 76
  isl_Latn: 77
  ita_Latn: 78
  jav_Latn: 79
  jpn_Jpan: 80
  kab_Latn: 81
  kac_Latn: 82
  kam_Latn: 83
  kan_Knda: 84
  kas_Arab: 85
  kas_Deva: 86
  kat_Geor: 87
  kaz_Cyrl: 88
  kbp_Latn: 89
  kea_Latn: 90
  khk_Cyrl: 91
  khm_Khmr: 92
  kik_Latn: 93
  kin_Latn: 94
  kir_Cyrl: 95
  kmb_Latn: 96
  kmr_Latn: 97
  knc_Arab: 98
  knc_Latn: 99
  kor_Hang: 100
  ktu_Latn: 101
  lao_Laoo: 102
  lij_Latn: 103
  lim_Latn: 104
  lin_Latn: 105
  lit_Latn: 106
  lmo_Latn: 107
  ltg_Latn: 108
  ltz_Latn: 109
  lua_Latn: 110
  lug_Latn: 111
  luo_Latn: 112
  lus_Latn: 113
  lvs_Latn: 114
  mag_Deva: 115
  mai_Deva: 116
  mal_Mlym: 117
  mar_Deva: 118
  min_Latn: 119
  mkd_Cyrl: 120
  mlt_Latn: 121
  mni_Beng: 122
  mos_Latn: 123
  mri_Latn: 124
  mya_Mymr: 125
  nld_Latn: 126
  nno_Latn: 127
  nob_Latn: 128
  npi_Deva: 129
  nso_Latn: 130
  nus_Latn: 131
  nya_Latn: 132
  oci_Latn: 133
  ory_Orya: 134
  pag_Latn: 135
  pan_Guru: 136
  pap_Latn: 137
  pbt_Arab: 138
  pes_Arab: 139
  plt_Latn: 140
  pol_Latn: 141
  por_Latn: 142
  prs_Arab: 143
  quy_Latn: 144
  ron_Latn: 145
  run_Latn: 146
  rus_Cyrl: 147
  sag_Latn: 148
  san_Deva: 149
  sat_Olck: 150
  scn_Latn: 151
  shn_Mymr: 152
  sin_Sinh: 153
  slk_Latn: 154
  slv_Latn: 155
  smo_Latn: 156
  sna_Latn: 157
  snd_Arab: 158
  som_Latn: 159
  sot_Latn: 160
  spa_Latn: 161
  srd_Latn: 162
  srp_Cyrl: 163
  ssw_Latn: 164
  sun_Latn: 165
  swe_Latn: 166
  swh_Latn: 167
  szl_Latn: 168
  tam_Taml: 169
  taq_Latn: 170
  taq_Tfng: 171
  tat_Cyrl: 172
  tel_Telu: 173
  tgk_Cyrl: 174
  tha_Thai: 175
  tir_Ethi: 176
  tpi_Latn: 177
  tsn_Latn: 178
  tso_Latn: 179
  tuk_Latn: 180
  tum_Latn: 181
  tur_Latn: 182
  twi_Latn: 183
  uig_Arab: 184
  ukr_Cyrl: 185
  umb_Latn: 186
  urd_Arab: 187
  uzn_Latn: 188
  vec_Latn: 189
  vie_Latn: 190
  war_Latn: 191
  wol_Latn: 192
  xho_Latn: 193
  ydd_Hebr: 194
  yor_Latn: 195
  yue_Hant: 196
  zgh_Tfng: 197
  zsm_Latn: 198
  zul_Latn: 199

inference:
  max_sequence_length: 512
  pooling: "logsumexp"
